"""empty message

Revision ID: 6e8c0569f8fa
Revises: d031dba50ad7
Create Date: 2018-06-19 17:51:36.321796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8c0569f8fa'
down_revision = 'd031dba50ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('money', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_index(op.f('ix_user_money'), 'user', ['money'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_money'), table_name='user')
    op.drop_column('user', 'money')
    # ### end Alembic commands ###
