"""empty message

Revision ID: bfb226b35364
Revises: e8e6e561f24b
Create Date: 2018-06-19 17:52:27.058814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb226b35364'
down_revision = 'e8e6e561f24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('desc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'desc')
    # ### end Alembic commands ###
