"""empty message

Revision ID: d031dba50ad7
Revises: 61cb6a5405ff
Create Date: 2018-06-19 17:50:45.640833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd031dba50ad7'
down_revision = '61cb6a5405ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('weight', sa.Float(), nullable=True))
    op.create_index(op.f('ix_user_weight'), 'user', ['weight'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_weight'), table_name='user')
    op.drop_column('user', 'weight')
    # ### end Alembic commands ###
